[payload, base, locks, scenario] = System.argv()
true = Path.expand(payload) == Path.expand(Application.app_dir(:tightbeam))
false = File.exists?(base)
{:ok, _} = Application.ensure_all_started(:exqlite)
{:ok, _} = Application.ensure_all_started(:crypto)
Application.put_env(:ex_unit, :assert_receive_timeout, 1_000)
Application.put_env(:tightbeam, :autostart, false)
Application.put_env(:tightbeam, :base_dir, base)
System.put_env("TIGHTBEAM_LOCAL_HOST_NAME", "testhost")
Tightbeam.CommandExecutionsFixture.run_case!(String.to_integer(scenario), base, locks)
