[payload, base, locks, proof, encoded] = System.argv()
true = Path.expand(payload) == Path.expand(Application.app_dir(:tightbeam))
false = File.exists?(base)
{:ok, _} = Application.ensure_all_started(:exqlite)
{:ok, _} = Application.ensure_all_started(:crypto)
Application.put_env(:ex_unit, :assert_receive_timeout, 1_000)
Application.put_env(:tightbeam, :autostart, false)
Application.put_env(:tightbeam, :local_host_name, "testhost")
Application.put_env(:tightbeam, :base_dir, base)
Process.put(:schema_locks, locks)
raw = JSON.decode!(encoded)
opts = %{activated: raw["activated"], boundary: raw["boundary"]}
Tightbeam.SchemaShapeRuntimeFixture.proof!(proof, base, opts)
IO.puts("schema-shape-cold: ok")
